name: Compile Typst Documents

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and install Typst
      run: |
        TYPST_VERSION="0.11.0"
        wget https://github.com/typst/typst/releases/download/v$TYPST_VERSION/typst-x86_64-unknown-linux-musl.tar.xz
        tar -xf typst-x86_64-unknown-linux-musl.tar.xz
        sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/

    - name: Compile all Typst files
      run: |
        find . -name "*.typ" -exec typst compile {} \;

    - name: Upload compiled PDFs
      uses: actions/upload-artifact@v4
      with:
        name: compiled-pdfs
        path: |
          **/*.pdf
